version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: smartbin_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always

  redis:
    image: redis:7
    container_name: smartbin_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
