# Generated by Django 6.0.4 on 2026-06-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_activity_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='status',
            field=models.CharField(db_index=True, default='idle', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_employee',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='reward',
            name='icon_category',
            field=models.CharField(choices=[('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('telecom', 'Telecom'), ('retail', 'Retail'), ('cash', 'Cash'), ('grocery', 'Grocery'), ('entertainment', 'Entertainment'), ('voucher', 'Voucher'), ('premium', 'Premium')], default='voucher', max_length=50),
        ),
    ]
