# Generated by Django 6.0.4 on 2026-06-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_profile_redemption_level_reward_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('cafe', 'Cafe'), ('restaurant', 'Restaurant'), ('telecom', 'Telecom'), ('retail', 'Retail'), ('cash', 'Cash'), ('grocery', 'Grocery'), ('entertainment', 'Entertainment'), ('voucher', 'Voucher'), ('premium', 'Premium')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='reward',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
