# Generated by Django 6.0.4 on 2026-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_reward_category_alter_reward_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemedreward',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
