# Generated by Django 6.0.4 on 2026-06-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_redeemedreward_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='material_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('aluminum', 'Aluminum'), ('glass', 'Glass'), ('cardboard', 'Cardboard'), ('newspaper', 'Newspaper')], default='plastic', max_length=50),
        ),
    ]
