# Generated by Django 6.0.4 on 2026-07-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_activity_material_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fcm_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_activity_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='milestone_points',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='redemption_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='streak_count',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='bin',
            name='compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='api.compound'),
        ),
        migrations.AddField(
            model_name='bin',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
