# Generated by Django 6.0.4 on 2026-07-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_profile_fcm_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(db_index=True, max_length=50, unique=True)),
                ('points_per_g', models.FloatField(default=0.0)),
                ('co2_per_g', models.FloatField(default=0.0)),
            ],
        ),
    ]
