# Generated by Django 6.0.4 on 2026-07-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_materialconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='material_type',
            field=models.CharField(choices=[('metal', 'Metal'), ('non_metal', 'Non-Metal'), ('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('trash', 'Trash')], default='plastic', max_length=50),
        ),
    ]
