# Generated by Django 6.0.4 on 2026-07-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_activity_material_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='reward',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
